### PR TITLE
Task/tbq 26 tbq 26 as a user of the program i want register myself

### PR DESCRIPTION
**Pull request by Kornilchenko**
add registration

### CODE REVIEW

**Review by Tsurkan — COMMENTED** [review]
Nice registration. BUT I believe that it is necessary to translate the application logic into a Command Pattern. I wrote the beginning in TBQ-8, you need to combine... And what about adding to the base? Postgres or H2.

**Review by Tsurkan — APPROVED** [review]
Registration works well. I would like to see the work with the base, but for now it will do.

**Comment by ali-ded** [comment]
The code is working. It will be necessary to merge with TBQ-4 and take the Command pattern as a basis. User data should be stored in the database.

**Review by ali-ded — APPROVED** [review]
The code is working. It will be necessary to merge with TBQ-4 and take the Command pattern as a basis. User data should be stored in the database.

**Pull request merged**
